contentDir = "content"
copyright = "Copyright Harfenlabor 2021"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
identifier = "news"
name = "News"
url = "/news"
weight = 1
[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 2
[[menu.main]]
identifier = "Barberini harp project"
name = "Barberini harp project"
parent = "projects"
url = "/projects/barberini"
weight = "1"
[[menu.main]]
identifier = "Harfenlabor lectures"
name = "Harfenlabor lectures"
parent = "projects"
url = "/projects/lectures"
weight = "2"
[[menu.main]]
identifier = "HL Editions"
name = "HL Editions"
parent = "projects"
url = "/projects/editions"
weight = "3"
[[menu.main]]
identifier = "Podcast: Between the Strings"
name = "Podcast: Between the Strings"
parent = "projects"
url = "/projects/podcast"
weight = "4"
[[menu.main]]
identifier = "research"
name = "research"
url = "/research"
weight = 3
[[menu.main]]
identifier = "organology"
name = "organology"
parent = "research"
url = "/research/organology"
weight = "1"
[[menu.main]]
identifier = "performance practice"
name = "performance practice"
parent = "research"
url = "/research/performance"
weight = "2"
[[menu.main]]
identifier = "musicology"
name = "musicology"
parent = "research"
url = "/research/musicology"
weight = "3"
[[menu.main]]
identifier = "HL editions"
name = "HL editions"
parent = "research"
url = "/research/HLeditions"
weight = "4"
[[menu.main]]
identifier = "iconography"
name = "iconography"
parent = "research"
url = "/research/iconography"
weight = "5"
[[menu.main]]
identifier = "sociology of art"
name = "sociology of art"
parent = "research"
url = "/research/sociology"
weight = "6"
[[menu.main]]
identifier = "timeline"
name = "timeline"
url = "/timeline"
weight = 4
[[menu.main]]
identifier = "map"
name = "map"
url = "/map"
weight = 5
[[menu.main]]
identifier = "index"
name = "index"
url = "/indextag"
weight = 6
[[menu.main]]
identifier = "search"
name = "search"
url = "/search"
weight = 7
[[menu.main]]
identifier = "about"
name = "about"
url = "/aboutpage"
weight = 8
[outputs]
baseURL = "harfenlabor.netlify.app"
disableLanguages = ["Fr"]
disqusShortname = ""
home = ["HTML", "RSS", "JSON"]
paginate = "6"
summaryLength = "15"
theme = "Harfenlabor"
themesDir = "../.."
title = "Harfenlabor"
[params]
author = "Harfenlabor"
description = ""
google_analytics_id = ""
logo = "images/logo.png"
post_share = true
[[params.Projects.projects]]
description = "A podcast series on early harp in music, from Medieval to contemporary. Hosted by Margret Köll, Between the Strings brings dialogue and music related to early harp. Varied people on the music scene bring rare insights into their working processes, ways of thinking, influences and experiences. "
title = "Podcast: Between the Strings"
[[params.Projects.projects]]
description = "By commissioning new works for Historical Harp through HL Editions, Harfenlabor aims to contribute to articulating a contemporary language of performance practice for the instrument. In collaboration with contemporary composers and performers, Harfenlabor intends to develop a new performative and interpretive plane for the instrument and keep its repertoire alive. "
title = "HL Editions"
[[params.Projects.projects]]
description = "The Barberini Harp is the most important surviving Italian Baroque harp. This chromatic harp with three parallel rows of strings was constructed in 1632-33 for the harpist Marco Marazzoli by the instrument maker Girolamo Acciari and the wood-carver Giovanni Tubi under the patronage of Cardinal Antonio Barberini.    As we still lack crucial understanding of this famous harp, Harfenlabor’s Barberini Harp Project intends to share and initiate research on this harp in the fields of organology, musicology, and performance practice.    This publication presents three stages of the Barberini Harp Project: Convening in Roma in 2016, Interviews with Experts, and Examinations."
title = "Barberini Harp Project"
[[params.Projects.projects]]
description = "Historical harp practice demands an ongoing engagement between scientific knowledge and artistic creation. Harfenlabor Lectures series offers a space for sharing multi-disciplinary knowledge on Historical Harp, whilst encouraging and supporting discussion and debate among diverse musicians, scientists, artists and instrument makers."
title = "Harfenlabor Lectures"
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
