contentDir = "content"
copyright = "Copyright Harfenlabor 2021"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[menu]
  [[menu.main]]
  identifier = "news"
  name = "news"
  url = "/news"
  weight = 1
  [[menu.main]]
  identifier = "projects"
  name = "projects"
  url = "/projects"
  weight = 2
  [[menu.main]]
  identifier = "Barberini harp project"
  name = "Barberini harp project"
  url = "/projects/barberini"
  parent = "projects"
  weight = "1"
  [[menu.main]]
  identifier = "Haydn’s  Folk Harp"
  name = "Haydn’s  Folk Harp"
  url = "/projects/haydn"
  parent = "projects"
  weight = "2"
  [[menu.main]]
  identifier = "lectures"
  name = "lectures"
  url = "/projects/lectures"
  parent = "projects"
  weight = "3"
  [[menu.main]]
  identifier = "research"
  name = "research"
  url = "/research"
  weight = 3
  [[menu.main]]
  identifier = "organology"
  name = "organology"
  url = "/research/organology"
  parent = "research"
  weight = "1"
  [[menu.main]]
  identifier = "performance practice"
  name = "performance practice"
  url = "/research/performance"
  parent = "research"
  weight = "2"
  [[menu.main]]
  identifier = "musicology"
  name = "musicology"
  url = "/research/musicology"
  parent = "research"
  weight = "3"
  [[menu.main]]
  identifier = "HL editions"
  name = "HL editions"
  url = "/research/HLeditions"
  parent = "research"
  weight = "4"
  [[menu.main]]
  identifier = "iconography"
  name = "iconography"
  url = "/research/iconography"
  parent = "research"
  weight = "5"
  [[menu.main]]
  identifier = "sociology of art"
  name = "sociology of art"
  url = "/research/sociology"
  parent = "research"
  weight = "6"
  [[menu.main]]
  identifier = "timeline"
  name = "timeline"
  url = "/timeline"
  weight = 4
  [[menu.main]]
  identifier = "map"
  name = "map"
  url = "/map"
  weight = 5
  [[menu.main]]
  identifier = "index"
  name = "index"
  url = "/indextag"
  weight = 6
  [[menu.main]]
  identifier = "search"
  name = "search"
  url = "/search"
  weight = 7
  [[menu.main]]
  identifier = "mediathek"
  name = "mediathek"
  url = ""
  weight = 8
  [[menu.main]]
  identifier = "about"
  name = "about"
  url = "/aboutpage"
  weight = 9

[projects]
[projects.Barberini_Harp_Project]
description = "the Barberini Harp Project is a…"
[projects.Haydns_Folk_Harp]
description = "the Haydn’s Folk Harp is a…"
[projects.Harfenlabor_Lectures]
description = "the Harfenlabor Lectures is a…"

[markup.goldmark.renderer]
unsafe = true
[outputs]
baseURL = "https://harfenlabor.netlify.com"

disableLanguages = ["Fr"]

disqusShortname = ""
home = ["HTML", "RSS", "JSON"]
paginate = "6"
summaryLength = "15"
theme = "Harfenlabor"
themesDir = "../.."
title = "Harfenlabor"
[params]
author = "Harfenlabor"
description = ""
google_analytics_id = ""
logo = "images/logo.png"
post_share = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
