[projects]
[projects.Barberini_Harp_Project]
description = "the Barberini Harp Project is a…"
[projects.Haydns_Folk_Harp]
description = "the Haydn’s Folk Harp is a…"
[projects.Harfenlabor_Lectures]
description = "the Harfenlabor Lectures is a…"
