[Barberini_Harp_Project]
description = "the Barberini Harp Project is a…"
[Haydns_Folk_Harp]
description = "the Haydn’s Folk Harp is a…"
[Harfenlabor_Lectures]
description = "the Harfenlabor Lectures is a…"

[[Barberini]]
icon = "ti-facebook"
link = "#"
[[Haydn]]
icon = "ti-facebook"
link = "#"
